version: '3'

services:
  spark:
    image: local_spark:latest
    container_name: spark
    hostname: spark
    ports:
      - 4040:4040
      - 8080:8080
      - 8888:8888
      - 9870:9870
      - 7077:7077
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - db_network

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    hostname: cassandra
    restart: always
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Test
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - db_network
    mem_limit: 4g

  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - db_network
    mem_limit: 4g

networks:
  db_network:
    name: db_network
    driver: bridge
